<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Product>neukeeper</Product>
    <Title>neukeeper</Title>
    <Description>Dotnet tool for updating dependencies automatically</Description>
    <Authors>Stephen Brown</Authors>
    <RepositoryUrl>https://github.com/evolvedlight/neukeeper</RepositoryUrl>
    <PackageProjectUrl>https://github.com/evolvedlight/neukeeper</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryType>git</RepositoryType>
    <IncludeSource>true</IncludeSource>
    <DebugType>embedded</DebugType>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>neukeeper</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <PackageOutputPath>./nupkg</PackageOutputPath>
    <ToolCommandName>neukeeper</ToolCommandName>
    <PackAsTool>true</PackAsTool>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <PackageTags>DotnetTool;DependencyUpdater;Automation;GitHub;Bitbucket;DependencyManagement;NuGet;MSBuild;CommandLineTool</PackageTags>
    <PackageIcon>icon.png</PackageIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Diagnostics" Version="8.3.2" />
    <PackageReference Include="CsvHelper" Version="33.0.1" />
    <PackageReference Include="DotNetOutdatedTool.Core" Version="4.6.4" />
    <PackageReference Include="McMaster.Extensions.CommandLineUtils" Version="4.1.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.0" />
    <PackageReference Include="Tenekon.MSBuild.Packaging.ProjectBuildInPackage" Version="2.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\providers\github\github.csproj" PrivateAssets="all" />
    <ProjectReference Include="..\providers\bitbucket\bitbucket.csproj" PrivateAssets="all" />
    <ProjectReference Include="..\shared\shared.csproj" PrivateAssets="all" />
  </ItemGroup>

  <PropertyGroup>
    <NoProjectBuildInPackageWelcome>false</NoProjectBuildInPackageWelcome>
  </PropertyGroup>

  <PropertyGroup>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>


  <ItemGroup>
    <None Include="..\README.md">
        <Pack>True</Pack>
        <PackagePath>\</PackagePath>
    </None>
    <None Include="icon.png" Pack="true" PackagePath="" />
  </ItemGroup>


  <ItemGroup>
    <None Update="icon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
